### ISSUE TITLE
Invoice PDF depends on HiveMind

### ISSUE THREAD

**Issue by jenshp** [moqui/PopCommerce#26] opened 2016-11-18 16:22 UTC
When attempting to generate the PDF for an invoice in PopcAdmin/Accounting/Invoice/EditInvoice.xml secreen and HiveMind is not installed, I get following error:
Problem accessing /fop/apps/hmadmin/Accounting/Invoice/PrintInvoice. Reason:

    Could not find subscreen or transition or file/content [PrintInvoice] under screen [component://webroot/screen/webroot/apps.xml] while finding url for path [apps, hmadmin, Accounting, Invoice, PrintInvoice] under from screen [component://webroot/screen/webroot.xml]

**Comment by jonesde** [comment] 2016-11-18 18:22
This was caused by a bad path in the EditInvoice.xml screen in SimpleScreens, ie should be using the appRoot field but wasn't. It is fixed in commit #9eda861 in SimpleScreens.

**Closed by jonesde** 2016-11-18 18:22 UTC
